---
- name: Download Heritrix
  get_url: url=http://builds.archive.org/maven2/org/archive/heritrix/heritrix/3.2.0/heritrix-3.2.0-dist.tar.gz dest=/tmp

- name: Unzip Heritrix
  unarchive: src=/tmp/heritrix-3.2.0-dist.tar.gz dest=/home/dcic copy=no owner=dcic group=dcic

- name: Copy heritrix script into profile.d
  copy: src=../files/heritrix dest=/etc/profile.d/heritrix

- name: Make executable
  acl: name=/home/dcic/heritrix-3.2.0/bin/heritrix entity=dcic etype=user permissions=rwx state=present

- name: Copy heritrix logo
  copy: src=../files/heritrix-logo.png dest=/home/dcic/heritrix-3.2.0

- name: Create launcher on DCIC desktop
  copy: src=../files/heritrix.desktop dest=/home/dcic/Desktop owner=dcic group=dcic
